In [1]:
import pandas as pd
df=pd.read_csv(r"C:\Users\bobkw\Desktop\FYP_Data.csv")
print(df)

    Gender  Hand   Forearm  Cheek  Comfort
0        1   33.6     33.0   34.1        2
1        1   33.5     33.6   34.2        2
2        1   33.1     32.9   33.4        1
3        1   33.0     32.6   32.9        1
4        1   33.4     33.2   33.8        2
5        1   33.4     33.3   34.0        2
6        1   34.1     32.8   33.9        2
7        1   32.8     32.7   33.5        1
8        1   33.6     33.4   34.2        2
9        1   33.4     33.5   34.1        2
10       1   34.3     33.8   34.6        3
11       1   33.4     33.6   34.3        3
12       1   34.0     32.9   34.4        2
13       0   34.2     33.6   34.6        1
14       0   33.8     33.2   34.7        2
15       0   34.6     34.2   35.4        3
16       0   33.9     33.7   34.8        3
17       0   34.6     34.5   34.8        3
18       0   33.5     33.5   34.2        2
19       0   34.3     33.3   34.6        2
20       0   33.7     33.8   35.0        2
21       0   33.8     33.4   34.5        2
22       0 

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
y=df.Comfort
x=df.drop('Comfort',axis=1)

In [3]:
df.head()

Gender  Hand   Forearm  Cheek  Comfort
0       1   33.6     33.0   34.1        2
1       1   33.5     33.6   34.2        2
2       1   33.1     32.9   33.4        1
3       1   33.0     32.6   32.9        1
4       1   33.4     33.2   33.8        2

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
x_train.head()

Gender  Hand   Forearm  Cheek
67       0   34.4     34.1   34.7
16       0   33.9     33.7   34.8
14       0   33.8     33.2   34.7
44       1   33.0     33.5   33.9
19       0   34.3     33.3   34.6

In [5]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=3)
svclassifier.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [6]:
y_pred = svclassifier.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 1  1  0]
 [ 0 10  1]
 [ 0  2  6]]
             precision    recall  f1-score   support

          1       1.00      0.50      0.67         2
          2       0.77      0.91      0.83        11
          3       0.86      0.75      0.80         8

avg / total       0.82      0.81      0.80        21



In [7]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
#print("Precision:",metrics.precision_score(y_test, y_pred))

Accuracy: 0.8095238095238095
